# This workflow will do a clean install of node and go dependencies, and run the CI scripts

name: wl-gammarelay CI

on:
  push:
    branches: '*'
    tags:
      - v*
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.17.6"]
    steps:
    - uses: actions/checkout@v2
    - name: Use Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2.1.3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install wayland
      run: sudo apt-get install -y libwayland-dev
    - run: make
    - run: go test ./...
